server:
  port: 8085

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/schedlr
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

    # API Endpoints

schedlr:
    dev:
      url: http://localhost:8081/schedlr/
    prod:
      url: http://prod.server.com/schedlr/