server:
  port: 8085

spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/schedlr
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

schedlr:
  dev:
    url: http://localhost:8083/schedlr/

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://schedlr-aws.cvu48ycmk8x0.ap-southeast-2.rds.amazonaws.com:3306/schedlr
    username: root
    password: schedlr10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

schedlr:
  prod:
    url: http://3.104.211.161:8083/schedlr/